### ISSUE TITLE
Download not working

### ISSUE THREAD

**Issue by brejchajan** [gronat/streetget#1]
When I run the example `streetget info 50.0833 14.4167`, streetget says Panorama not found. Furthermore, when I try to download Prague dataset using `streetget box 50.0833 14.4167 300 200 -itd -z 0,1,3 -D /local/myData Prague_all`, nothing is downloaded at all. It seems to me, that only empty database file is stored. I tried many other combinations of different input coordinates, but without any change.

After deeper analysis of the code I figured out, that method getMeta inside panorama.py obtains response 200 OK, but the response content is always empty. Therefore, no metadata are retrieved at all. It seems that google changed their API. Do you know any simple method how to tune the query in getMeta to make it work again? Thanks a lot!

**Comment by brejchajan** [comment]
Ok, it seems that I chose wrong places to test. Prague Old Town Square works OK.

**Comment by mcimpoi** [comment]
Should be fixed with the last PR. 
Alternatively, try "circle" instead of box.
